### 2.1.1 Simple

In [ ]:
# import library of torch
import torch

In [ ]:
# generat a tensor
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
# the shape of array
x.shape

torch.Size([12])

In [4]:
# the amount of arrays
x.numel()

12

In [5]:
# the way that changes the shape of arrays but does not change the amount of elements
X = x.reshape(3,4)
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [ ]:
# create the  tensor of zeros shaped (2,3,4)
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [7]:
# the tensor of one shaped (2,3,4)
torch.ones((2,3,4))


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [8]:
'''
the tensor that Each element is a standard Gaussian distribution 
with a mean of 0 and a standard deviation of 1
'''
torch.randn(3,4)

tensor([[-2.2108,  0.0352,  0.5575,  1.4288],
        [-0.5381,  2.4111,  0.1248, -2.1582],
        [ 0.2783, -1.0549,  0.5776,  0.2446]])

In [9]:
# create tensor by myself
torch.tensor([[2,1,4,3],[1,2,3,4],[4,3,2,1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

### 2.1.2 Operator

In [10]:
x = torch.tensor([[1.0,2,4,8]])
y = torch.tensor([2,2,2,2])
x + y,x - y, x * y, x / y, x ** y

(tensor([[ 3.,  4.,  6., 10.]]),
 tensor([[-1.,  0.,  2.,  6.]]),
 tensor([[ 2.,  4.,  8., 16.]]),
 tensor([[0.5000, 1.0000, 2.0000, 4.0000]]),
 tensor([[ 1.,  4., 16., 64.]]))

In [11]:
# exp
torch.exp(x)

tensor([[2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03]])

In [ ]:
# Merge tensors by different axis
X = torch.arange(12,dtype=torch.float32).reshape(3,4)
Y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((X,Y),dim=0),torch.cat((X,Y),dim=1)


(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [14]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [15]:
# sum for all elemnts
X.sum()

tensor(66.)

### 2.1.3 Broadcasting mechanism

In [16]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(2).reshape(1,2)
a,b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [17]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

### 2.1.4 Index and Slice

In [ ]:
X[-1],X[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [21]:
X[1,2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
X[0:2,:] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

### 2.1.5 Saving memory

In [25]:
before = id(Y)
Y =Y+X
id(Y) == before , id(Y)

(False, 1965628833312)

In [ ]:
# solution 1
Z = torch.zeros_like(Y)
print('id(Z):',id(Z))
Z[:] = X + Y
print('id(Z):',id(Z))

id(Z) 1965611246480
id(Z) 1965611246480


In [27]:
# solution 2
before = id(X)
X +=Y
id(X) == before

True

### 2.1.6 Convert to other objects

In [28]:
A = X.numpy()
B = torch.tensor(A)
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [29]:
a = torch.tensor([3.5])
a , a.item(),float(a),int(a)

(tensor([3.5000]), 3.5, 3.5, 3)