### 2.5.1 A simple example

In [2]:
import torch
x = torch.arange(4.0)
x

tensor([0., 1., 2., 3.])

In [3]:
# set the storage place of the gradient
x.requires_grad_(True)
x.grad

In [4]:
# calculate the y
y = 2*torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [ ]:
#  By calling the backpropagation function 
# to automatically calculate the gradients of y with respect to each component of x, 
# and print these gradients
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [6]:
# Quickly verify that the gradient is correct
x.grad == 4*x

tensor([True, True, True, True])

In [7]:
# By default ,PyTorch accumulates gradients and we need to clear the previous values
x.grad.zero_()
print('x:',x)
y = x.sum()
print('y:',y)
y.backward()
x.grad

x: tensor([0., 1., 2., 3.], requires_grad=True)
y: tensor(6., grad_fn=<SumBackward0>)


tensor([1., 1., 1., 1.])

### 2.5.2 Backpropagation of non-scalar variables


In [8]:
x.grad.zero_()
y = x*x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])